### ISSUE TITLE
File Extractor Needs to Decompress Files

### ISSUE THREAD

**Issue by SymphoniaLauren** [pnvnd/Tales-of-Destiny-2#1]
Extractor gives the file extensions to files while they are still compressed, meaning that if you wanted to [comptoe -d "filename" "filename"], it will only work if you change the name of the file when you decompress. There's also no way to tell if a file is compressed or decompressed when they are like this.

**Comment by pnvnd** [comment]
After extracting FPB with `python tod2_ps2.py 1`, use `python unpack_folders.py` to organize files in `FPB` folder to `FILE` folder and decompress files if needed.  Tested and working as of v8.
