### ISSUE TITLE
questions about using this patch

### ISSUE THREAD

**Issue by miowng** [pnvnd/Tales-of-Destiny-2#64]
Hi, I can't found any .pnach file inside
may I know how to enable this patch on pcsx2 ?

**Comment by SymphoniaLauren** [comment]
To use the patch, you need to apply it to your ISO using XDelta. No pnach file.

**Comment by miowng** [comment]
So the xdelta file is created by using comptoe.exe inside ps2/v9.7z ?
I still unable to apply patch to iso file

my action:
1, open xdeltaUI.exe
2, select create patch 
3, choose my iso file as original file
4, choose comptoe.exe as modified file
5, click patch to get .xdelta file
6, click apply patch 
7, select .xdelta file create before as patch
8, select iso file as source file
9, click patch

where am I wrong? can you please correct me about it?

**Comment by SymphoniaLauren** [comment]
Latest release of the WIP patch is [here](https://github.com/lifebottle/Tales-of-Destiny-2/releases), under Tales of Destiny 2 (PS2) - English Patch v0.0.24. Compto.exe is a tool that is used to uncompress files that are in the game.

What you do is:

- Download TOD2_PS2_PATCH.zip
- Unzip Contents to get the xdelta patch
- Run Xdelta.ui
- Using the "Apply Patch" option:

> Select "TOD2_PATCH_v0.0.24.xdelta" as your patch
> Select your Tales of Destiny 2 ISO as your Source File
> Specify where you want the resulting ISO saved.
Example:
![image](https://user-images.githubusercontent.com/77311570/134459875-9c5affce-4ed1-4c1a-b090-48eb20eaf325.png)

Do keep in mind that the patch as it is is incomplete. If you want to keep up with patches, you'll need to use a clean ISO for a new patch.
If you have anymore questions, always feel free to stop by the Life Bottle RnD discord server: https://discord.gg/6C3dS2B4

**Comment by miowng** [comment]
Alright, thankyou very much!
it's really help me
